<wsdl:definitions name="EROTIMATAService" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/TDY/EROTIMATAService" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/TDY/EROTIMATAService" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EROTIMATAService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EROTIMATAService_plt">
    <plt:role name="EROTIMATAService_role">
      <plt:portType name="tns:EROTIMATAService_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EROTIMATAService" schemaLocation="../../ADAPTERS/EROTIMATAService/EROTIMATAService_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="Kps6DeltioErothmataCollection_msg">
        <wsdl:part name="Kps6DeltioErothmataCollection" element="top:Kps6DeltioErothmataCollection"/>
    </wsdl:message>
    <wsdl:portType name="EROTIMATAService_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:Kps6DeltioErothmataCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>