<wsdl:definitions
     name="ANADOXOIWriteService"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/TDY/ANADOXOIWriteService"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/TDY/ANADOXOIWriteService"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ANADOXOIWriteService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ANADOXOIWriteService_plt" >
    <plt:role name="ANADOXOIWriteService_role" >
      <plt:portType name="tns:ANADOXOIWriteService_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ANADOXOIWriteService" schemaLocation="../../ADAPTERS/ANADOXOIWriteService/write_Anadoxoi_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="KpsAnadoxoiCollection_msg">
        <wsdl:part name="KpsAnadoxoiCollection" element="top:KpsAnadoxoiCollection"/>
    </wsdl:message>
    <wsdl:portType name="ANADOXOIWriteService_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:KpsAnadoxoiCollection_msg"/>
        </wsdl:operation>
        <wsdl:operation name="insert">
            <wsdl:input message="tns:KpsAnadoxoiCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
