<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/Common/GetRowPrivs" name="GetRowPrivs-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GetRowPrivs.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/Common/GetRowPrivs"/>
    <wsdl:binding name="GetRowPrivs_ptt-binding" type="get:GetRowPrivs_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/Common/GetRowPrivs">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetRowPrivs">
            <soap:operation soapAction="GetRowPrivs"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>