<wsdl:definitions name="TDY_read" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/TDY/TDY_read" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/TDY/TDY_read" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/TDY_read" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="TDY_read_plt">
    <plt:role name="TDY_read_role">
      <plt:portType name="tns:TDY_read_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/TDY_read" schemaLocation="../../ADAPTERS/TDY_read/TDY_read_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="selectByPrimaryKey_inputParameters">
        <wsdl:part name="selectByPrimaryKey_inputParameters" element="top:Kps6YpoergaPrimaryKey"/>
    </wsdl:message>
    <wsdl:message name="Kps6YpoergaCollection_msg">
        <wsdl:part name="Kps6YpoergaCollection" element="top:Kps6YpoergaCollection"/>
    </wsdl:message>
    <wsdl:portType name="TDY_read_ptt">
        <wsdl:operation name="selectByPrimaryKey">
            <wsdl:input message="tns:selectByPrimaryKey_inputParameters"/>
            <wsdl:output message="tns:Kps6YpoergaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>