<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/E555/E555CreateService" name="E555CreateService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="E555CreateService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/E555/E555CreateService"/>
    <wsdl:binding name="E555CreateService_ptt-binding" type="e55:E555CreateService_ptt" xmlns:e55="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/E555/E555CreateService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="E555CreateService">
            <soap:operation soapAction="E555CreateService"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>