<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/E555/E555SearchService" name="E555SearchService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="E555SearchService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/E555/E555SearchService"/>
    <wsdl:binding name="E555SearchService_ptt-binding" type="e555-sp:E555SearchService_ptt" xmlns:e555-sp="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/E555/E555SearchService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="E555SearchService">
            <soap:operation soapAction="E555SearchService"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>