<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/TDY/STATUSService" name="STATUSService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="STATUSService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/TDY/STATUSService"/>
    <wsdl:binding name="STATUSService_ptt-binding" type="stat:STATUSService_ptt" xmlns:stat="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/TDY/STATUSService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="STATUSService">
            <soap:operation soapAction="STATUSService"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>