<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/E524/CheckUpdateService" name="CheckUpdateService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CheckUpdateService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/E524/CheckUpdateService"/>
    <wsdl:binding name="CheckUpdateService_ptt-binding" type="chec:CheckUpdateService_ptt" xmlns:chec="http://xmlns.oracle.com/pcbpel/adapter/db/EnlightIT/E524/CheckUpdateService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CheckUpdateService">
            <soap:operation soapAction="CheckUpdateService"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>